-- 日本語UTF-8, LF



USE [master]
GO

-- __NAME__MDF__      : [__DATABASE_NAME__]
-- __FULL_NAME__MDF__ :  C:\Program Files\Micorsoft SQL Server\MSSQL10\50.MSSQLSERVER\MSSQL\DATA\[__DATABASE_NAME__].mdf
-- __NAME__LDF__      : [__DATABASE_NAME__]_log
-- __FULL_NAME__LDF__ : C:\Program Files\Micorsoft SQL Server\MSSQL10\50.MSSQLSERVER\MSSQL\DATA\[__DATABASE_NAME__]_log.ldf
CREATE DATABASE [__DATABASE_NAME__] ON PRIMARY 
( 
	NAME = N'__NAME__MDF__', 
	FILENAME = N'__FULL_NAME__MDF__', 
	SIZE = 3072KB, 
	MAXSIZE = UNLIMITED, 
	FILEGROWTH = 1024KB 
) LOG ON 
(
	NAME = N'__NAME__LDF__', 
	FILENAME = N'__FULL_NAME__LDF__', 
	SIZE = 1024KB, 
	MAXSIZE = 2048GB, 
	FILEGROWTH = 10% 
)
GO

ALTER DATABASE [__DATABASE_NAME__] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [__DATABASE_NAME__].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [__DATABASE_NAME__] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [__DATABASE_NAME__] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [__DATABASE_NAME__] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [__DATABASE_NAME__] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [__DATABASE_NAME__] SET ARITHABORT OFF 
GO

ALTER DATABASE [__DATABASE_NAME__] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [__DATABASE_NAME__] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [__DATABASE_NAME__] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [__DATABASE_NAME__] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [__DATABASE_NAME__] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [__DATABASE_NAME__] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [__DATABASE_NAME__] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [__DATABASE_NAME__] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [__DATABASE_NAME__] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [__DATABASE_NAME__] SET  DISABLE_BROKER 
GO

ALTER DATABASE [__DATABASE_NAME__] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [__DATABASE_NAME__] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [__DATABASE_NAME__] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [__DATABASE_NAME__] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [__DATABASE_NAME__] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [__DATABASE_NAME__] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [__DATABASE_NAME__] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [__DATABASE_NAME__] SET RECOVERY FULL 
GO

ALTER DATABASE [__DATABASE_NAME__] SET  MULTI_USER 
GO

ALTER DATABASE [__DATABASE_NAME__] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [__DATABASE_NAME__] SET DB_CHAINING OFF 
GO

ALTER DATABASE [__DATABASE_NAME__] SET  READ_WRITE 
GO



